### ISSUE TITLE
 FATAL  this.nuxt.plugin is not a function  

### ISSUE THREAD

**Issue by IamTinashe** [alexitaylor/Nuxt-Express-Socket.io-Template#1]
> at ModuleContainer.module.exports (io\index.js:8:13)

Got this error when I tried to run it. How can I solve it?

**Comment by FullZero5** [comment]
`this.nuxt.hook('close', () => new Promise((resolve) => server.close(resolve)))`

**Comment by FullZero5** [comment]
> > at ModuleContainer.module.exports (io\index.js:8:13)
> 
> Got this error when I tried to run it. How can I solve it?

this.nuxt.hook('close', () => new Promise((resolve) => server.close(resolve)))

**Comment by altoroid** [comment]
Replace this.nuxt.plugin with this.nuxt.hook. It worked for me.
